// "What's New": short, friendly notes about updates, newest first.
// audience: 'all' (everyone) or 'admin' (admins only). Keep them about WHAT CHANGED and WHERE TO FIND IT.
// Never mention how the app is built or hosted, AI model names, settings or keys.

export const NEWS = [
  {
    id: '2026-09-29-form-required', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'Fixed: "Phone field is not required" on forms where it was',
    what: 'Reported by <b>Chris Barnett</b>, and the first fix to come straight out of a False alarm report. Ticking <b>Required</b> in the Duda form editor does <i>not</i> add a required attribute to the field — Duda marks the <b>row</b> around it (<span class="mono">class="dmforminput … required"</span>), validates in its own code, and puts a star on the label. The check was only looking at the field itself, so it called <b>every</b> Duda form field optional, including the ones that had been required all along. It now reads the row, the star on the label or placeholder, and Duda’s hidden label field — any one of them is enough — and still catches a phone field that genuinely is optional.',
    where: ['Websites already scanned show <b>⚠ A check was corrected — rescan</b> and the affected items are marked, so nobody keeps chasing it.', 'Rescan and the false ones go. A form where the phone field really is optional is still flagged.', 'This is what the False alarm queue is for — if a check looks wrong to you, mark the item <b>False alarm</b> and say why.'],
    link: '#/help/suggest', linkText: 'How reports work',
  },
  {
    id: '2026-09-29-fa-reports', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'A False alarm is now a bug report you can follow',
    what: 'Marking an item <b>False alarm</b> is you telling the app that one of its checks got it wrong — which is the most useful thing it ever learns about itself. That used to vanish into an admin-only list you never saw again. Now it is a report with your name on it. Your reason is posted as a <b>comment on the audit item</b>, so the next person to open it reads why it was dismissed instead of arguing with it again. The item itself shows <b>you reported this as a false alarm</b> with where it has got to, and the audit list carries a small <b>Reported:</b> chip. When an admin moves it you are <b>told — with their note</b>, not just a status — on the bell, on your desktop, in Slack and by email. And you can <b>answer back</b> on your own report: if you think the verdict is wrong, say so, and the admins hear it. The statuses now say what happened to the <i>check</i>: <b>New</b>, <b>Checking</b>, <b>Audit Adjusted</b>, <b>True False Alarm</b>, <b>Won’t change</b>. Admins are asked for a note on every move, because “True False Alarm” with no explanation tells you nothing.',
    where: ['Mark an item <b>False alarm</b> as usual — the reason box is the report.', 'Follow yours under <b>💡 → My false alarms</b>, or on the audit item itself.', 'Admins: <b>💡 → False alarms</b> is the full queue, opening on <b>New + Checking</b>, with <b>Most reported checks</b> at the top so the one worth fixing next is obvious.', 'Nothing to migrate — reports filed under the old New / Ongoing / Done / Skip statuses are read straight into the new ones.'],
    link: '#/help/suggest', linkText: 'How reports work',
  },
  {
    id: '2026-09-29-fa-adjusted', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'One report fixed, every affected website flags itself',
    what: 'The point of the new <b>Audit Adjusted</b> status: it is not just a label. The moment an admin marks a report Audit Adjusted, the app remembers <b>which check</b> was corrected and <b>when</b> — and every website that was scanned before that moment and is carrying items from that check says so on its own page, with the admin’s explanation quoted, and marks each affected item <b>⚠ This check was corrected — rescan</b>. No app update needed: triaging the report <i>is</i> what publishes the correction. So one person hitting a bad item, and one admin agreeing with them, is enough to clear that item off all 800 audits — and the person who reported it is told that their report is what caused it.',
    where: ['Admins: <b>💡 → False alarms</b> → set a report to <b>Audit Adjusted</b>. The box tells you what it is about to flag before you save.', 'On <b>Audits</b>, affected websites get <b>⚠ A check was corrected — rescan</b> in the Scan column.', 'On a website: an orange note above the audit items, and a mark on each affected item.', 'Items already marked <b>Done</b>, <b>False alarm</b> or <b>On hold</b> are left alone — nothing is deleted, and a rescan replaces the rest.'],
    link: '#/help/scan', linkText: 'What happens on a rescan',
  },
  {
    id: '2026-09-29-corrected-checks', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'When a check turns out to be wrong, the audit says so',
    what: 'Until now an update could only <b>add</b> checks, and the note on an old audit said "new checks available — rescan if you like". But a check can also be <b>corrected</b>, and then the items it already produced are not work at all — they are wrong, sitting in somebody’s list looking exactly like everything else. Nothing is deleted behind your back (an item may carry your comments, a status, a number somebody quoted in Slack), so it is <b>marked</b> instead. The website shows an orange note saying how many items came from the corrected check and what was wrong with it, every affected item carries <b>⚠ This check was corrected — rescan</b>, and there is deliberately <b>no "Not now"</b> — a wrong item is not optional noise. Rescanning replaces them; anything that was a real problem comes straight back with its number.',
    where: ['On a website with an old scan: the note is at the top of <b>Audit items</b>, above the list.', 'Affected items are marked in the list and again when you open them, so nobody starts fixing one by accident.', 'On <b>Audits</b>, the <b>Scan</b> column flags the website with <b>⚠ A check was corrected — rescan</b>.', 'Items you already marked <b>Done</b>, <b>False alarm</b> or <b>On hold</b> are left alone — you made your decision, it stands.', 'The first correction to use this is the font one, in the note below.'],
    link: '#/help/scan', linkText: 'Scanning and rescanning',
  },
  {
    id: '2026-09-29-font-weights', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'Bold and SemiBold are the same font again',
    what: 'When a designer uploads a custom typeface, Duda serves each weight as its own font file with the weight in the name — <b>BarcolaExpanded-Bold</b>, <b>BarcolaExpanded-SemiBold</b>, <b>BarcolaExpanded-Medium</b>, <b>BarcolaExpanded-Regular</b>. The audit was reading those as <b>four different typefaces</b>, so a website using one font in four weights came back with a hundred items saying the headings were in the wrong font. They are now read as <b>one typeface with four weights</b>. The Fonts tab shows a single card per typeface with its weights listed underneath, and an audit item names the family — "Title in Magistral" rather than "Title in Magistral-Medium" — so <b>approving a font covers every weight of it</b> in one go. Only text in a typeface that genuinely is not part of the design is flagged now.',
    where: ['On a website: <b>Reference data</b> → <b>Fonts used on the website</b> — one card per typeface, with <b>Weights: Bold · SemiBold · Medium</b> underneath.', 'Audit items sit under the <b>Design</b> category and name the exact words to fix.', 'Already scanned websites keep their old result until you rescan — the website will show a <b>new checks available</b> note.', 'Approving a typeface (<b>Reference data</b> → <b>Business Info</b> → <b>＋ Add or exclude a value</b> → <b>Typeface</b>) now covers all of its weights, whichever one you type.'],
    link: '#/help/fonts', linkText: 'How the font check works',
  },
  {
    id: '2026-09-29-our-layer', date: '2026-09-29', audience: 'all', tag: 'Audits',
    title: 'Your own additions and exceptions, beside Business Info',
    what: 'Clients rebrand, add a second line, change their email. Business Info still comes from Duda and is <b>never edited here</b> — that stays the reference, fresh on every scan — but there is now a layer beside it that your team owns and a rescan never touches. It runs <b>both ways</b>: mark a value <b>correct for this website</b> (a second shop line, an owner\u2019s personal email, a typeface chosen on purpose) so it is never flagged; or mark one <b>not correct</b> (your own agency address sitting in a client\u2019s Business Info, a retired number) so it <i>is</i> flagged even though Duda lists it. Duda\u2019s copy still shows those, struck through, so you can see what Duda says and what you decided. And approving a value <b>closes the open items that flagged it</b> \u2014 it tells you how many first, writes the reason on each one, and they can be reopened.',
    where: ['On a website: <b>Reference data</b> \u2192 <b>Business Info</b> \u2192 <b>\uff0b Add or exclude a value</b>.', 'Phone, email, business name, social link or typeface \u2014 with a note the next person will want to read.', 'Every entry shows who added it, when, why, and its history. <b>Edit</b> changes it, <b>Remove</b> puts it back to being checked normally.', 'Rescans ask nothing: Duda refreshes, your layer stays.'],
    link: '#/help/approved', linkText: 'How the layer works',
  },
  {
    id: '2026-09-28-due-in', date: '2026-09-28', audience: 'all', tag: 'Comments',
    title: 'Dates say the day, and "ours to answer" says when',
    what: 'Two small things that were costing you a calculation. <b>Every date now carries the day of the week</b> — "Sat, Sep 26, 12:01 AM" — because knowing something landed on a Saturday is half the explanation of why nothing has happened to it. And a client comment that is ours to answer but <b>not overdue yet</b> used to read "ours to answer · 70h", which looks like three days of neglect; it now reads <b>"ours to answer · due in 2h"</b>, with the full explanation on hover. Both mean the same thing — the client spoke last and the 24 hours excludes weekends — but one of them answers the question. The Slack digest also now says <b>overdue</b> rather than "unanswered", since that is what it counts.',
    where: ['Anywhere a date is shown — Audits, comments, the activity log.', 'On a conversation: <b>waiting on us · 31h</b> is late, <b>ours to answer · due in 2h</b> is not late yet.', 'Hover either badge for when it came in and when it counts as overdue.'],
    link: '#/help/comments-duda', linkText: 'How comments work',
  },
  {
    id: '2026-09-28-digest', date: '2026-09-28', audience: 'all', tag: 'Comments',
    title: 'One message per website, not one per comment',
    what: 'A client leaving twenty comments in a sitting used to mean <b>twenty Slack messages</b> once they went overdue — the fastest way to teach everyone to ignore Slack. It is now <b>one message per website</b>: the business name, how many are unanswered, how long the worst one has waited, then the five oldest listed with their ages and the rest counted. After that the website <b>goes quiet</b> and speaks again only when things are genuinely worse — more comments overdue, or the oldest crossing another day — and never more than once a day. The thinking: whoever picks up the 48-hour comment is looking at the rest anyway. And when more than five websites fall behind at once, it becomes a <b>single roll-up</b> rather than a message each.',
    where: ['Nothing to set up. The next alert arrives in the new shape.', 'The bell shows the same digest, with each comment on its own line.', 'Everything still appears on the page and the bell immediately — the quiet rule only governs Slack.', 'A website that gets fully answered is forgotten, so it alerts fresh if it falls behind again.'],
    link: '#/help/comments-duda', linkText: 'How the alert works',
  },
  {
    id: '2026-09-27-empty-threads', date: '2026-09-27', audience: 'all', tag: 'Comments',
    title: 'Empty conversations no longer count against you',
    what: 'Duda opens a conversation the moment somebody clicks to comment, before any words are typed, and a comment can be deleted afterwards — so the list was carrying cards with nothing on them, reading "Page unknown" with no text, and <b>counting towards "6 waiting"</b> and raising alerts nobody could act on. A conversation with nothing left in it is now <b>not shown, not counted and never alerts</b>, and deleted comments are dropped rather than shown as "(deleted)". Deleting the last comment no longer looks like fresh activity either — the clock stays where the last real comment left it. Separately, every conversation now says its own wait: <b>waiting on us · 31h</b> once it is overdue, or <b>ours to answer · 2h</b> when the client spoke last but the clock has not run out.',
    where: ['Nothing to do — the counts correct themselves as comments arrive.', 'Open any website in <b>Duda comments</b>: the wait is on each conversation, top right.', 'Under three days it counts in hours, because "31h" reads more urgently than "1 day".'],
    link: '#/help/comments-duda', linkText: 'How comments work',
  },
  {
    id: '2026-09-27-triage', date: '2026-09-27', audience: 'all', tag: 'Comments',
    title: 'Monday morning: who has been waiting longest',
    what: 'The comments list was ordered by whatever came in last, which is the wrong question after a weekend. It now leads with <b>who has been waiting longest</b>. A line at the top says how many client comments are waiting and on how many websites, and names the worst one with the date — red once anyone has waited two days. The list is ordered oldest-wait first, and each website shows the wait in plain terms: <b>1 waiting · 4 days</b>, with the badge getting louder at two days and louder again at three.',
    where: ['<b>Duda comments</b> — the line is above the list, before anything else.', '<b>Work through them, oldest first</b> filters to just the websites with someone waiting.', 'Weekends still do not count towards the wait, so a Friday comment is flagged on Monday, not Saturday.'],
    link: '#/help/comments-duda', linkText: 'How comments work',
  },
  {
    id: '2026-09-27-notif-tabs', date: '2026-09-27', audience: 'all', tag: 'Collaboration',
    title: 'The bell is sorted into tabs',
    what: 'Everything arrived in one list, so a client waiting for an answer sat between two finished scans. The bell now has tabs — <b>All</b>, <b>Duda comments</b>, <b>Mentions &amp; replies</b>, <b>Scans</b>, <b>Audits</b> and <b>Admin</b> — each with a count, and a tab only appears when there is something in it.',
    where: ['Click the bell. <b>Duda comments</b> is the one to check first: a client waiting on an answer.', '<b>Mentions &amp; replies</b> is anything aimed at you personally.', 'Opening the bell still marks everything read, whichever tab you are on.'],
  },
  {
    id: '2026-09-26-duda-staff', date: '2026-09-26', audience: 'all', tag: 'Comments',
    title: 'Duda itself now says who is a designer',
    what: 'Duda knows exactly who is <b>staff</b> and who is a <b>customer</b> — it is the best answer there is, better than Slack and far better than guessing at email domains. It just has no way to list everyone: you can only ask about one person at a time. So the app now asks, automatically, the first time an address turns up in a comment, and keeps the answer for a month. A designer commenting from a personal Gmail is recognised as one of us <b>with nothing to set up</b>. There is also a button that asks about <b>everyone who has ever commented</b> at once, which arrives at your list of designers from the other end.',
    where: ['Nothing to do — it works on its own from the next comment.', 'To see the whole picture: <b>Duda comments</b> → <b>👥 Who is on the team</b> → <b>Ask Duda about everyone who has commented</b>.', 'It lists who came back as staff, who as a customer, and who has no Duda account; Duda is asked in batches, so click again to carry on.', 'Slack is still worth reading in — it catches the people Duda has never heard of, like someone who works on the sites but has no Duda login.'],
    link: '#/help/comments-duda', linkText: 'How comments work',
  },
  {
    id: '2026-09-26-slack-team', date: '2026-09-26', audience: 'all', tag: 'Comments',
    title: 'Slack decides who is one of us',
    what: 'Every Duda comment is marked <b>client</b> or <b>team</b>, and only a client left waiting ever raises an alert. Until now that was guessed from email domains, which breaks the moment a teammate comments from a personal Gmail — and that comment then looks like a client waiting for an answer. There is now a <b>Team from Slack</b> button on the Duda comments page: it reads your Slack workspace once and keeps the list, so anyone in it counts as team whatever address they write from. <b>Slack guests are deliberately left as clients</b> — a client invited into a shared channel is a Slack member too, and counting them as team would silence exactly the comments this is here to catch. Bots and deactivated accounts are skipped, and <b>not the client?</b> still overrides everything.',
    where: ['<b>Duda comments</b> → <b>👥 Team from Slack</b> → <b>Read the Slack workspace</b>. Admins only, once for the whole team.', 'The panel lists who was counted as team and who was left as a guest, so you can check before trusting it.', 'Somebody joined or left? Open it again and <b>Read Slack again</b>.', 'It needs the Slack app to have <b>users:read</b> and <b>users:read.email</b>; if they are missing the panel says which to add.'],
    link: '#/help/comments-duda', linkText: 'How comments work',
  },
  {
    id: '2026-09-26-clarification', date: '2026-09-26', audience: 'all', tag: 'Audits',
    title: 'Asking a question now actually asks somebody',
    what: '"For clarification" was a status you could park an item on and nobody would ever know. Picking it now <b>asks what the question is</b>, and the question is posted as a comment on the item so the answer has somewhere to land. Type <b>@</b> to tag a member, or the new <b>@Admins</b> to reach every admin in one go \u2014 everyone tagged gets it on the bell, on their desktop and in Slack. @Admins is worked out when you send it, so it always means whoever is an admin today. And a website with a question outstanding now says so on the <b>Audits</b> list: <b>\u2753 N waiting on an answer</b> under its name, with the <b>For clarification</b> tile at the top working as a filter.',
    where: ['Set any audit item to <b>For clarification</b> \u2014 the question box opens straight away.', 'Type <b>@Admins</b> to tag all of them at once, or <b>@</b> and a name for one person.', 'On <b>Audits</b>, click the <b>For clarification</b> tile to see only the websites waiting on an answer.', 'Inside a website, the <b>For clarification</b> chip filters the items the same way.'],
    link: '#/help/statuses', linkText: 'How the statuses work',
  },
  {
    id: '2026-09-26-bi-history', date: '2026-09-26', audience: 'all', tag: 'Audits',
    title: 'The audit now knows what Business Info used to say',
    what: 'Business Info was treated as timeless truth, so a client changing their email quietly turned everything we knew into a lie: the old address still on the website looked like a detail nobody recognised, and the new one \u2014 correct \u2014 got flagged until somebody approved it by hand. Every scan now <b>records Business Info and what changed since last time</b>. Three things follow. A website still showing a detail Duda no longer carries reads <i>"Still using the old email address \u2014 Business Info was changed on 12 Aug 2026"</i>, with the current value as Expected, and sits at a new <b>Outdated</b> severity between Critical and Warning \u2014 so a client-change sweep is one filter. An <b>approval retires itself</b> the moment Business Info catches up and carries that value officially, and an approval for something that has just <i>stopped</i> being official is flagged for a second look. And the dates are all on a new <b>Business Info history</b> tab.',
    where: ['On a website, open <b>Reference data</b> \u2192 <b>Business Info history</b> for every change with its date, and what is no longer official.', 'The <b>Outdated</b> chip appears above the audit items when there is something to show \u2014 click it to see only those.', 'Retired approvals are under <b>Approvals that retired themselves</b> on the Business Info tab.', 'History starts from your next scan, so give it one rescan before expecting it to know anything.'],
    link: '#/help/bi-history', linkText: 'How it works',
  },
  {
    id: '2026-09-26-crosscheck', date: '2026-09-26', audience: 'all', tag: 'Audits',
    title: 'Audit items now show what we already knew',
    what: 'When the audit flags a phone number or an email, the answer is often already written down \u2014 the client left a comment in the Duda editor saying "use our new number", or somebody marked the same value a False alarm on another website last month. Neither was ever shown next to the item that needed it. A contact item now carries both: <b>the comment that mentions the value</b>, marked client or team, and <b>any past False alarm on the same value</b> with the reason somebody wrote. One thing is decided for you: an item <b>nobody has touched</b> whose value a <b>client</b> asked about is set to <b>For clarification</b>, because there is a question outstanding and it should not sit in the default list looking like ordinary work.',
    where: ['Open any contact audit item \u2014 the blue block under the finding is what we already knew.', 'It links straight to the conversation in <b>Duda comments</b>.', 'An item moved automatically says so, so it never looks like somebody else changed it.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-26-filters', date: '2026-09-26', audience: 'all', tag: 'Audits',
    title: 'Filters can no longer hide your whole audit',
    what: 'If a filter was left on — say <b>Design</b>, from clicking <b>Show them in Audit items</b> on the Fonts tab — the list could read "No audit items match these filters" while the chips above still said <b>Critical 5</b>, which looks like the audit has broken. Three fixes: the <b>severity chips now count what clicking them would actually show</b>, so they read <b>Critical 0</b> when something else is filtering; a filter that is doing something is <b>outlined</b>; and the empty message says how many items are hidden and by which filters, with a <b>Clear filters</b> button. Filters also reset when you open a different website, instead of following you around.',
    where: ['Nothing to set up.', 'If a list ever looks empty, the message under it names the filters and the button clears them in one click.'],
  },
  {
    id: '2026-09-26-one-item-per-thing', date: '2026-09-26', audience: 'all', tag: 'Checks',
    title: 'One thing to fix, one audit item',
    what: 'Two kinds of double-counting are gone. <b>Fonts:</b> a menu whose six links are all in the wrong typeface used to be six audit items with six near-identical selectors; it is now <b>one item</b> pointing at the menu itself and naming every link inside it — <i>"5 navigation links in Titillium Web… Found: Car Detailing · RV Detailing and Coating · Additional Service Areas · Ocean City, MD · Bethany Beach, DE"</i>. <b>Contact info:</b> the same wrong phone number can be found three ways on one button — in the words, in the tel: link, and in an aria-label. That is one thing to fix, so it is one item now, which mentions in passing where else the number appears. A genuinely <i>different</i> wrong number in the aria-label is still its own item, because it is a different fix.',
    where: ['Rescan a website and the count drops — same faults, counted once.', 'On a grouped font item, <b>Show on page</b> highlights the whole menu or section, and <b>Found</b> lists every piece of text inside it.', 'Links in body text now get their typeface checked too, not just navigation links and buttons.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-25-fonts-tab', date: '2026-09-25', audience: 'all', tag: 'Checks',
    title: 'The font check now uses the website\u2019s own settings',
    what: 'The first version counted fonts — "Navigation use 2 different typefaces — Titillium Web (24 places), Yantramanav (14 places)" — which is true and useless. It now reads the website\u2019s <b>own design settings</b>: the font it sets for the body text, and for each heading level <b>H1 to H6</b>. Those are the website\u2019s fonts. Anything in a font that <b>isn\u2019t one of them</b> is an audit item naming the actual words, on the page they are on, so <b>Show on page</b> finds them. A heading set in the body font is no longer flagged — it is still the website\u2019s font. Reference data now has a second tab beside Business Info, <b>Fonts used on the website</b>: the design\u2019s fonts, and anything else that turned up on the pages.',
    where: ['On a website, open <b>Reference data</b> → the <b>Fonts used on the website</b> tab, beside Business Info.', 'The first block is the design\u2019s fonts; below it is anything that isn\u2019t part of it.', '<b>Show them in Audit items</b> filters the list below to the Design category.', 'Websites scanned before today show the blue "new checks" note — rescan to pick this up.'],

    link: '#/help/fonts', linkText: 'How the Fonts tab works',
  },
  {
    id: '2026-09-25-one-item', date: '2026-09-25', audience: 'all', tag: 'Checks',
    title: 'One problem, one audit item',
    what: 'A phone button that <b>shows</b> the right number and <b>dials</b> a wrong one used to raise two items back to back — "dials a number that is not in Business Info" and "shows one number but dials another" — the same fault, counted twice. It is now a single item that says both: <i>"Phone button shows one number but dials another, and the number it dials is not in Business Info."</i> Email links behaved the same way and were fixed with it.',
    where: ['Nothing to do. Rescan a website and the pair collapses into one item.', 'Your open counts will drop slightly as a result — the same faults, counted once.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-24-check-notice', date: '2026-09-24', audience: 'all', tag: 'Checks',
    title: 'An audit tells you when new checks arrive',
    what: 'When we add checks, finished audits are left exactly as they are — nothing is recalculated behind your back, and nothing appears overnight. But an audit scanned last month was judged against a shorter list, and until now there was no way to tell. Now there is: a website scanned before the newest checks shows a <b>blue note at the top of its Audit items</b> saying how many checks were added, with the full list of what they look for. Rescanning is your call, per website. If you do, <b>every item you already have is kept</b> — anything marked <b>Done</b>, <b>False alarm</b> or <b>On hold</b> keeps its state, its number and its comments — and the new checks simply add new <b>Open</b> items. None of them count as critical, so your critical numbers do not move.',
    where: ['Open any website you scanned before today — the note is at the top of <b>Audit items</b>, above everything else.', 'Click <b>See what was added</b> to read the full list before deciding.', '<b>Rescan now</b> runs it; <b>Not now</b> hides the note on that website, for you only.', 'To find them all at once: on <b>Audits</b>, click <b>✨ Scanned before the newest checks</b> in the toolbar. Each one is also flagged in the <b>Scan</b> column.', 'Want them all done? Filter to them, then <b>Rescan all shown</b>.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-24-new-checks', date: '2026-09-24', audience: 'all', tag: 'Checks',
    title: 'The scan now checks fonts properly — and nine other things',
    what: 'From the QA sheet, now answered automatically on every scan. The big one is <b>typefaces</b>: the scan works out which font each piece of text really ends up in — following the stylesheet, inline styles and inheritance, and ignoring CSS that matches nothing — then checks <b>navigation, titles, paragraphs and buttons</b> separately. If the titles are in two fonts, it says so and names the exact headings. It also spots a font the page never loads, and one loaded from outside Google Fonts or Envato. Also new: <b>more than one FAQ block</b> per page, <b>local business schema</b> missing from the home page, <b>messy page addresses</b> (capitals, underscores, a number on the end from a duplicated page, leftovers like "copy-of"), a <b>thank-you page</b> with no call button or way home, <b>no analytics tag</b> (or an old UA- one), <b>two contact forms</b> on a page, a <b>phone field that is not required</b>, <b>buttons that go nowhere</b>, a <b>missing favicon</b>, and anything still loading over <b>http://</b>.',
    where: ['Rescan any website; the new items appear with everything else.', 'On the website page, filter <b>Category</b> by <b>Design</b>, <b>Schema</b> or <b>Meta / SEO</b> to see them together.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-24-drafts-tab', date: '2026-09-24', audience: 'all', tag: 'Comments',
    title: 'The websites still in build finally have a home',
    what: '<b>Live DR Sites</b> only ever listed <b>published</b> websites — but clients review and comment on the <b>draft</b>, before launch, so the sites with the most going on were invisible. There is now a <b>Not published yet</b> tab beside it, listing websites still in build, sorted so the ones with a client waiting come first. Both tabs now have a <b>Comments</b> column, so you can see where somebody is waiting without opening anything.',
    where: ['Click <b>Live DR Sites</b> → the <b>Not published yet</b> tab.', 'It starts on the ones <b>with comments</b>. Switch the box for those in Audits, or every unpublished website.', 'The <b>Comments</b> column is on both tabs; click the count and it opens that website and flashes the new conversations.'],
    link: '#/live/unpublished', linkText: 'Open it',
  },
  {
    id: '2026-09-24-threads', date: '2026-09-24', audience: 'all', tag: 'Comments',
    title: 'Comments now read like conversations',
    what: 'A conversation shows its <b>number</b>, the <b>opening comment</b>, and its <b>replies grouped underneath</b> — the way it looks in the Duda editor, instead of a flat list. <b>Resolved conversations are hidden by default</b>, so a tidied-up website no longer looks like a wall of "Resolved". You can search inside a website\'s comments, and anything we only joined half-way through says so plainly.',
    where: ['<b>Duda comments</b> → pick a website.', 'Tick <b>Show resolved</b> to see the finished ones.', 'Type in <b>Search inside these comments</b> to find one you half-remember.'],
    link: '#/help/comments-duda', linkText: 'How it works',
  },
  {
    id: '2026-09-24-duda-comments', date: '2026-09-24', audience: 'all', tag: 'Comments',
    what: 'Comments left in the <b>Duda editor</b> — by the client on their draft, or by us internally — now appear in the app on their own. There is a new <b>Duda comments</b> page in the top menu listing every website in the Duda account that has them: <b>published or not, on the Audits list or not</b>. Nothing has to be switched on per website, and you do not have to add a site to Audits just to read its comments. Each conversation shows the page, the device, who wrote it, when, and whether it is resolved, and each comment is marked <b>client</b> or <b>internal</b>.',
    title: 'Client comments come to you now',
    where: ['<b>Admins first:</b> <b>Duda comments</b> → <b>⚙ Duda connection</b> → <b>Connect to Duda</b>. One click, for the whole account.', 'Then click <b>Duda comments</b> in the top menu.', 'Filter by <b>New to you</b>, <b>Waiting on us</b>, <b>Unresolved</b> or <b>All</b>, or search by website name or site ID.', 'Pick a website on the left to read its conversations; opening it clears your own <b>new</b> count.', 'Leave the page open — new comments land on it by themselves, no refreshing.', 'Turns out it needs work? <b>Add to Audits</b> is on the same screen.'],
    link: '#/comments', linkText: 'Open Comments',
  },
  {
    id: '2026-09-24-comment-waiting', date: '2026-09-24', audience: 'all', tag: 'Comments',
    title: 'One alert: a client left waiting',
    what: 'New comments deliberately do <b>not</b> notify anyone — with hundreds of websites that would be constant noise. There is exactly one exception: when a <b>client</b> comment has gone <b>24 hours with nobody on the team replying</b> and is still unresolved, the admins are told once. Replying in Duda or resolving the conversation both count as answering, and weekends do not count — a Friday-evening comment is flagged on Monday, not Saturday.',
    where: ['Nothing to set up. A red dot on <b>Duda comments</b> in the top menu means somebody is waiting.', 'The <b>Waiting on us</b> filter lists them.', 'Inside a website, a waiting conversation is outlined in red and sits at the top.'],
    link: '#/help/comments-duda', linkText: 'How it works',
  },
  {
    id: '2026-09-23-removed', date: '2026-09-23', audience: 'all', tag: 'Audits',
    title: 'Removing an audit now leaves a record, not a hole',
    what: 'The <b>✕</b> on a row takes an audit off the list — it never touches the website itself in Duda. It now asks <b>why</b> (a short reason is required, which is also a moment to stop if you clicked by mistake), tells the assignee and the person who added it, and keeps a card on the new <b>Removed from Audits</b> page: business name, <b>site ID</b>, how far the audit had got, who removed it, when, and the reason. So "what was that website, and why is it gone?" has an answer months later — and if the site comes back, <b>Audit again</b> puts its ID straight into the Add dialog for a fresh scan.',
    where: ['Open <b>Audits</b> → <b>Removed from Audits</b> in the line under the heading.', 'Removing: the <b>✕</b> at the end of a row, as before — it now asks for a reason.', 'Search the page by business name, site ID, reason or person.', 'Older activity that used to say "(deleted website)" now shows the real name with a <b>removed from Audits</b> tag.'],
    link: '#/removed', linkText: 'Open Removed from Audits',
  },
  {
    id: '2026-09-23-ownership', date: '2026-09-23', audience: 'all', tag: 'Audits',
    title: 'Nobody can quietly take your audit',
    what: 'Your work is now yours. Finish a website and it shows <b>✓ Marked Complete by you</b> with the date. If anyone <b>rescans</b> it, <b>reopens</b> it, or <b>reassigns</b> it to someone else, you\'re told <b>what happened and who did it</b> — in the bell, on the desktop and on Slack if you\'ve switched that on. And before a teammate can take a website off you, the app warns them how much you\'ve already closed, tells them you\'ll be notified, and asks for a short reason. That reason goes in your notification and in the website\'s Activity log.',
    where: ['Open any website: the completer\'s name is under the business name, and in the <b>Audits</b> list under the status pill.', 'Changed your mind? Change the <b>Assigned to</b> box or the status on the website page — you\'ll see the warning before it goes through.', 'Want it on Slack too? Avatar → <b>Your account</b> → tick <b>Also message me on Slack</b>.', 'The full record is on the website\'s <b>Activity log</b> tab.'],
    link: '#/help/ownership', linkText: 'How this works',
  },
  {
    id: '2026-09-23-stats', date: '2026-09-23', audience: 'all', tag: 'Team',
    title: 'Team stats: see what everyone has closed',
    what: 'A simple table of who did what: websites assigned to each person, how many are Complete, websites they marked Complete, audit items they closed as <b>Done</b>, and how many they tagged <b>False alarm</b>, <b>On hold</b> or <b>For clarification</b>. You can always see your own row; admins see everyone. Counting starts today, so older work isn\'t in the numbers.',
    where: ['Click <b>Members</b> (top right) → <b>📊 Team stats</b>.'],
    link: '#/help/stats', linkText: 'What the columns mean',
  },
  {
    id: '2026-09-23-who-is-who', date: '2026-09-23', audience: 'all', tag: 'Team',
    title: 'Always know who is who',
    what: 'Display names are now unique, so no two people can share one. <b>Click any name</b> (in a comment, a mention or the member list) to see their email, whether they\'re online and what they\'ve been working on. Mentions remember the person, so if someone renames themselves, older mentions show their new name; hover to see the name used at the time.',
    where: ['Click a name in a comment or an <b>@mention</b>.', 'Click <b>Members</b> (top right) to search and filter by <b>Everyone</b>, <b>Online now</b>, <b>Offline</b> and <b>Switched off</b>.', 'Changing your own name: avatar → <b>Your account</b>. If the name is taken you\'ll be asked to add a surname or initial.'],
  },
  {
    id: '2026-09-23-switch-off', date: '2026-09-23', audience: 'admin', tag: 'Admin',
    title: 'Switch an account off instead of deleting it',
    what: 'When somebody leaves, switch their account off. They can no longer sign in, but their name stays on every audit item, comment and scan, so you can still see who did what. You can switch it back on at any time.',
    where: ['Click <b>Members</b> → <b>Switch off</b> on that person.', 'Use the <b>Switched off</b> filter to see them.', 'Deleting for good is still there, but it removes their name from old items.'],
  },
  {
    id: '2026-09-23-scan-done', date: '2026-09-23', audience: 'all', tag: 'Audits',
    title: "You're told when a scan finishes",
    what: 'Submit a website for audit and get on with something else. When the scan finishes, the person who <b>added</b> the website and the person it is <b>assigned</b> to both get a notification with the number of audit items found: in the bell, on the desktop, and on Slack if they\'ve switched that on.',
    where: ['Click <b>+ Add website</b>, choose who to <b>Assign</b> it to, then <b>Add &amp; start audit</b>.', 'The dialog and the website page tell you that you\'ll be notified when it finishes.', 'Want it on Slack? Avatar → <b>Your account</b> → tick <b>Also message me on Slack</b>.', '<b>You are told about your own scans too</b> — start one, go and do something else, and the app calls you back. A <b>Rescan all shown</b> stays quiet.'],
  },
  {
    id: '2026-09-23-ai-credits', date: '2026-09-23', audience: 'all', tag: 'AI',
    title: 'More AI capacity, and it lasts much longer',
    what: 'The ✨ AI can now check far more websites in a day. It also works smarter: only text that could hide a problem is sent (a name that looks like another business, a place, contact details or filler text), so plain marketing copy and long blog posts no longer use up the day\'s credits. When one AI runs out, the next one carries on by itself.',
    where: ['Click the <b>light bulb</b> (top left) → <b>AI Status</b> to see the credits left today.', 'On a website\'s page, the scan summary now says how many text blocks were read and how many plain ones were skipped.'],
    link: '#/ai', linkText: 'Open AI Status',
  },
  {
    id: '2026-09-23-slack', date: '2026-09-23', audience: 'all', tag: 'Slack',
    title: 'Get your notifications on Slack',
    what: 'When someone mentions you, replies to you or assigns you an audit item, you can get a direct message on Slack as well as the bell. You don\'t need to install anything: it uses the Slack account with the same email you signed up with here.',
    where: ['Click your <b>avatar</b> (top right) → <b>Your account</b>.', 'Tick <b>Also message me on Slack</b> and click <b>Save</b>.', 'Click <b>Show a test notification</b>: you\'ll see the pop-up and get a Slack message from <b>Site Auditor</b>.', 'Not receiving it? Your Slack account must use the same email as your account here.'],
  },
  {
    id: '2026-09-23-verify-live', date: '2026-09-23', audience: 'all', tag: 'Audits',
    title: 'Check that your fixes are really live',
    what: 'After you fix items and publish the site in Duda, the app can scan the <b>published</b> website and confirm that the items you marked <b>Done</b> are really fixed there. It shows the item numbers that are fixed, and the ones still on the live site.',
    where: ['Open a website, stay on <b>Audit items</b>.', 'The <b>Live site check</b> box shows when the site was last published.', 'Click <b>🌐 Verify … Done items on live site</b>.'],
    link: '#/help/verify', linkText: 'How it works',
  },
  {
    id: '2026-09-23-false-alarm', date: '2026-09-23', audience: 'all', tag: 'Audits',
    title: 'Approve a value as correct for a website',
    what: 'Some values are intentional, like a client asking for forms to go to a different email. When you mark an item <b>False alarm</b>, you can now tick a box to say that value is correct for that website. Other open items with the same value are closed too, and future scans stop flagging it.',
    where: ['Open an audit item → <b>False alarm</b>.', 'Write the reason, keep the tick box on, and save.', 'Approved values are listed under <b>Reference data → Also correct for this website</b>, where you can remove them.'],
    link: '#/help/approved', linkText: 'Read more',
  },
  {
    id: '2026-09-22-find-element', date: '2026-09-22', audience: 'all', tag: 'Audits',
    title: 'Jump straight to the element: preview or editor',
    what: 'Every audit item now has <b>Show on preview</b> and <b>Show in editor</b> under its CSS selector, so you can go straight to the page you need to fix. A one-time bookmark can outline the exact element for you.',
    where: ['Open a website → <b>Audit items</b>.', 'Under the selector, click <b>▶ Show on preview</b> or <b>✎ Show in editor</b>.', 'Click the small <b>?</b> next to them to set up the <b>⌖ DSA Highlight</b> bookmark once.'],
    link: '#/help/find', linkText: 'Read more',
  },
  {
    id: '2026-09-22-one-scan', date: '2026-09-22', audience: 'all', tag: 'Audits',
    title: 'Only one scan per website at a time',
    what: 'If a teammate has a website queued or is scanning it, you\'ll see <b>Queued by …</b> or <b>Scanning by …</b> and the Rescan button is greyed out. No more two people scanning the same site and getting different results.',
    where: ['You\'ll see it on the <b>Audits</b> list, in the Scan column.', 'It frees up when they finish, or within a few minutes if their tab closed.'],
  },
  {
    id: '2026-09-22-add-ids', date: '2026-09-22', audience: 'all', tag: 'Audits',
    title: 'Add websites by pasting site IDs',
    what: 'You no longer need the full editor link. Paste site IDs (like <code>cb89784b</code>), one per line. Each one shows its business name as you type, so typos stand out.',
    where: ['Click <b>+ Add website</b> and paste the IDs.', 'Links still work, and you can mix both.'],
  },
  {
    id: '2026-09-22-editor-env', date: '2026-09-22', audience: 'all', tag: 'Settings',
    title: 'Choose where editor and preview links open',
    what: 'Some of the team prefer the agency editor address, others prefer Duda\'s. You can now pick your own; it only changes where your links take you.',
    where: ['Click your <b>avatar</b> → <b>Your account</b>.', 'Pick under <b>Open the Duda editor and previews on</b>, then <b>Save</b>.'],
  },
  {
    id: '2026-09-22-site-header', date: '2026-09-22', audience: 'all', tag: 'Audits',
    title: 'Last published date and a Live site button',
    what: 'A website\'s page now shows when it was last published in Duda, plus a <b>Live site ↗</b> button for the published website. The old "Preview" button is now called <b>Draft preview ↗</b>, because it shows the editor\'s version including unpublished changes.',
    where: ['Open any website: it\'s under the business name and along the top-right buttons.'],
  },
  {
    id: '2026-09-22-help', date: '2026-09-22', audience: 'all', tag: 'Help',
    title: 'A full Help guide, with an assistant',
    what: 'Everything about the app is now written down: statuses, scanning, audit items, Live DR Sites and more. You can also ask the Help assistant a question in your own words.',
    where: ['Click the <b>light bulb</b> (top left) → <b>Help</b>.', 'Search the guide, or type a question at the top.'],
    link: '#/help', linkText: 'Open Help',
  },
  {
    id: '2026-09-22-checks', date: '2026-09-22', audience: 'all', tag: 'Checks',
    title: 'Fewer false alarms, one new critical check',
    what: 'Blog "share this page" buttons and Google Maps links that carry only a place ID are no longer reported as another business, and LinkedIn profiles are read correctly. New rule: a <b>thank-you page that is not set to noindex</b> is now critical, while thank-you pages that are noindex are correct.',
    where: ['You\'ll see the difference on the next rescan of a website.'],
    link: '#/help/rules', linkText: 'What the checks look for',
  },
  {
    id: '2026-09-23-admin-slack', date: '2026-09-23', audience: 'admin', tag: 'Admin',
    title: 'See who can be reached on Slack',
    what: 'The Members list now shows <b>Slack ✓</b> or <b>No Slack match</b> for each person, so you can spot someone whose app email differs from their Slack email.',
    where: ['Click <b>Members</b> (top right).'],
  },
];

export const newsFor = (role) => NEWS.filter((n) => n.audience === 'all' || (n.audience === 'admin' && role === 'admin'));
export const latestNewsId = (role) => (newsFor(role)[0] || {}).id || '';
